# CMake generated Testfile for 
# Source directory: D:/03_Projects/01_Actives/HFText/core
# Build directory: D:/03_Projects/01_Actives/HFText/core/build-msvc
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(hftext_core_types_test "D:/03_Projects/01_Actives/HFText/core/build-msvc/Debug/hftext_core_types_test.exe")
  set_tests_properties(hftext_core_types_test PROPERTIES  _BACKTRACE_TRIPLES "D:/03_Projects/01_Actives/HFText/core/CMakeLists.txt;81;add_test;D:/03_Projects/01_Actives/HFText/core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(hftext_core_types_test "D:/03_Projects/01_Actives/HFText/core/build-msvc/Release/hftext_core_types_test.exe")
  set_tests_properties(hftext_core_types_test PROPERTIES  _BACKTRACE_TRIPLES "D:/03_Projects/01_Actives/HFText/core/CMakeLists.txt;81;add_test;D:/03_Projects/01_Actives/HFText/core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(hftext_core_types_test "D:/03_Projects/01_Actives/HFText/core/build-msvc/MinSizeRel/hftext_core_types_test.exe")
  set_tests_properties(hftext_core_types_test PROPERTIES  _BACKTRACE_TRIPLES "D:/03_Projects/01_Actives/HFText/core/CMakeLists.txt;81;add_test;D:/03_Projects/01_Actives/HFText/core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(hftext_core_types_test "D:/03_Projects/01_Actives/HFText/core/build-msvc/RelWithDebInfo/hftext_core_types_test.exe")
  set_tests_properties(hftext_core_types_test PROPERTIES  _BACKTRACE_TRIPLES "D:/03_Projects/01_Actives/HFText/core/CMakeLists.txt;81;add_test;D:/03_Projects/01_Actives/HFText/core/CMakeLists.txt;0;")
else()
  add_test(hftext_core_types_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(hftext_core_encoder_test "D:/03_Projects/01_Actives/HFText/core/build-msvc/Debug/hftext_core_encoder_test.exe")
  set_tests_properties(hftext_core_encoder_test PROPERTIES  _BACKTRACE_TRIPLES "D:/03_Projects/01_Actives/HFText/core/CMakeLists.txt;82;add_test;D:/03_Projects/01_Actives/HFText/core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(hftext_core_encoder_test "D:/03_Projects/01_Actives/HFText/core/build-msvc/Release/hftext_core_encoder_test.exe")
  set_tests_properties(hftext_core_encoder_test PROPERTIES  _BACKTRACE_TRIPLES "D:/03_Projects/01_Actives/HFText/core/CMakeLists.txt;82;add_test;D:/03_Projects/01_Actives/HFText/core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(hftext_core_encoder_test "D:/03_Projects/01_Actives/HFText/core/build-msvc/MinSizeRel/hftext_core_encoder_test.exe")
  set_tests_properties(hftext_core_encoder_test PROPERTIES  _BACKTRACE_TRIPLES "D:/03_Projects/01_Actives/HFText/core/CMakeLists.txt;82;add_test;D:/03_Projects/01_Actives/HFText/core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(hftext_core_encoder_test "D:/03_Projects/01_Actives/HFText/core/build-msvc/RelWithDebInfo/hftext_core_encoder_test.exe")
  set_tests_properties(hftext_core_encoder_test PROPERTIES  _BACKTRACE_TRIPLES "D:/03_Projects/01_Actives/HFText/core/CMakeLists.txt;82;add_test;D:/03_Projects/01_Actives/HFText/core/CMakeLists.txt;0;")
else()
  add_test(hftext_core_encoder_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(hftext_core_crc16_test "D:/03_Projects/01_Actives/HFText/core/build-msvc/Debug/hftext_core_crc16_test.exe")
  set_tests_properties(hftext_core_crc16_test PROPERTIES  _BACKTRACE_TRIPLES "D:/03_Projects/01_Actives/HFText/core/CMakeLists.txt;83;add_test;D:/03_Projects/01_Actives/HFText/core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(hftext_core_crc16_test "D:/03_Projects/01_Actives/HFText/core/build-msvc/Release/hftext_core_crc16_test.exe")
  set_tests_properties(hftext_core_crc16_test PROPERTIES  _BACKTRACE_TRIPLES "D:/03_Projects/01_Actives/HFText/core/CMakeLists.txt;83;add_test;D:/03_Projects/01_Actives/HFText/core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(hftext_core_crc16_test "D:/03_Projects/01_Actives/HFText/core/build-msvc/MinSizeRel/hftext_core_crc16_test.exe")
  set_tests_properties(hftext_core_crc16_test PROPERTIES  _BACKTRACE_TRIPLES "D:/03_Projects/01_Actives/HFText/core/CMakeLists.txt;83;add_test;D:/03_Projects/01_Actives/HFText/core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(hftext_core_crc16_test "D:/03_Projects/01_Actives/HFText/core/build-msvc/RelWithDebInfo/hftext_core_crc16_test.exe")
  set_tests_properties(hftext_core_crc16_test PROPERTIES  _BACKTRACE_TRIPLES "D:/03_Projects/01_Actives/HFText/core/CMakeLists.txt;83;add_test;D:/03_Projects/01_Actives/HFText/core/CMakeLists.txt;0;")
else()
  add_test(hftext_core_crc16_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(hftext_core_frame_test "D:/03_Projects/01_Actives/HFText/core/build-msvc/Debug/hftext_core_frame_test.exe")
  set_tests_properties(hftext_core_frame_test PROPERTIES  _BACKTRACE_TRIPLES "D:/03_Projects/01_Actives/HFText/core/CMakeLists.txt;84;add_test;D:/03_Projects/01_Actives/HFText/core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(hftext_core_frame_test "D:/03_Projects/01_Actives/HFText/core/build-msvc/Release/hftext_core_frame_test.exe")
  set_tests_properties(hftext_core_frame_test PROPERTIES  _BACKTRACE_TRIPLES "D:/03_Projects/01_Actives/HFText/core/CMakeLists.txt;84;add_test;D:/03_Projects/01_Actives/HFText/core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(hftext_core_frame_test "D:/03_Projects/01_Actives/HFText/core/build-msvc/MinSizeRel/hftext_core_frame_test.exe")
  set_tests_properties(hftext_core_frame_test PROPERTIES  _BACKTRACE_TRIPLES "D:/03_Projects/01_Actives/HFText/core/CMakeLists.txt;84;add_test;D:/03_Projects/01_Actives/HFText/core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(hftext_core_frame_test "D:/03_Projects/01_Actives/HFText/core/build-msvc/RelWithDebInfo/hftext_core_frame_test.exe")
  set_tests_properties(hftext_core_frame_test PROPERTIES  _BACKTRACE_TRIPLES "D:/03_Projects/01_Actives/HFText/core/CMakeLists.txt;84;add_test;D:/03_Projects/01_Actives/HFText/core/CMakeLists.txt;0;")
else()
  add_test(hftext_core_frame_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(hftext_core_modulator_test "D:/03_Projects/01_Actives/HFText/core/build-msvc/Debug/hftext_core_modulator_test.exe")
  set_tests_properties(hftext_core_modulator_test PROPERTIES  _BACKTRACE_TRIPLES "D:/03_Projects/01_Actives/HFText/core/CMakeLists.txt;85;add_test;D:/03_Projects/01_Actives/HFText/core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(hftext_core_modulator_test "D:/03_Projects/01_Actives/HFText/core/build-msvc/Release/hftext_core_modulator_test.exe")
  set_tests_properties(hftext_core_modulator_test PROPERTIES  _BACKTRACE_TRIPLES "D:/03_Projects/01_Actives/HFText/core/CMakeLists.txt;85;add_test;D:/03_Projects/01_Actives/HFText/core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(hftext_core_modulator_test "D:/03_Projects/01_Actives/HFText/core/build-msvc/MinSizeRel/hftext_core_modulator_test.exe")
  set_tests_properties(hftext_core_modulator_test PROPERTIES  _BACKTRACE_TRIPLES "D:/03_Projects/01_Actives/HFText/core/CMakeLists.txt;85;add_test;D:/03_Projects/01_Actives/HFText/core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(hftext_core_modulator_test "D:/03_Projects/01_Actives/HFText/core/build-msvc/RelWithDebInfo/hftext_core_modulator_test.exe")
  set_tests_properties(hftext_core_modulator_test PROPERTIES  _BACKTRACE_TRIPLES "D:/03_Projects/01_Actives/HFText/core/CMakeLists.txt;85;add_test;D:/03_Projects/01_Actives/HFText/core/CMakeLists.txt;0;")
else()
  add_test(hftext_core_modulator_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(hftext_core_demodulator_test "D:/03_Projects/01_Actives/HFText/core/build-msvc/Debug/hftext_core_demodulator_test.exe")
  set_tests_properties(hftext_core_demodulator_test PROPERTIES  _BACKTRACE_TRIPLES "D:/03_Projects/01_Actives/HFText/core/CMakeLists.txt;86;add_test;D:/03_Projects/01_Actives/HFText/core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(hftext_core_demodulator_test "D:/03_Projects/01_Actives/HFText/core/build-msvc/Release/hftext_core_demodulator_test.exe")
  set_tests_properties(hftext_core_demodulator_test PROPERTIES  _BACKTRACE_TRIPLES "D:/03_Projects/01_Actives/HFText/core/CMakeLists.txt;86;add_test;D:/03_Projects/01_Actives/HFText/core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(hftext_core_demodulator_test "D:/03_Projects/01_Actives/HFText/core/build-msvc/MinSizeRel/hftext_core_demodulator_test.exe")
  set_tests_properties(hftext_core_demodulator_test PROPERTIES  _BACKTRACE_TRIPLES "D:/03_Projects/01_Actives/HFText/core/CMakeLists.txt;86;add_test;D:/03_Projects/01_Actives/HFText/core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(hftext_core_demodulator_test "D:/03_Projects/01_Actives/HFText/core/build-msvc/RelWithDebInfo/hftext_core_demodulator_test.exe")
  set_tests_properties(hftext_core_demodulator_test PROPERTIES  _BACKTRACE_TRIPLES "D:/03_Projects/01_Actives/HFText/core/CMakeLists.txt;86;add_test;D:/03_Projects/01_Actives/HFText/core/CMakeLists.txt;0;")
else()
  add_test(hftext_core_demodulator_test NOT_AVAILABLE)
endif()
